accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^register$', views.register, name='register'),
    url(r'^information$', views.information, name='information'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^like$', views.like, name='like'),

]

persons/urls.py
from django.conf.urls import url

from . import views

app_name = 'persons'
urlpatterns = [
    url(r'^add_home$', views.addHome, name='add_home'),
    url(r'^base$', views.base, name='base'),
    url(r'^$', views.showHome, name='show_homes'),
    url(r'^yourHomes/$', views.yourHomes, name='yourHomes'),


    url(r'^(?P<id>[0-9]+)/$', views.remove_a_ana, name='remove_a_ana'),
    url(r'^(?P<id>[0-9]+)/$', views.updown, name='updown'),
    url(r'^(?P<id>[0-9]+)/$', views.add_a_ana, name='add_a_ana'),

    
    url(r'^home/(?P<home_id>[0-9]+)/$', views.detail_home, name='detail_home'),
    url(r'^image/(?P<img_id>[0-9]+)/delete/$', views.delete_image, name='delete_image'),
    url(r'^(?P<home_id>[0-9]+)/delete/$', views.home_delete, name='delete'),
    url(r'^(?P<home_id>[0-9]+)/edit/$', views.home_update, name='update'),
    url(r'^users/(?P<user_id>[0-9]+)/$', views.detail_user, name='users'),
    url(r'^formset$', views.formset_view, name='formset'),
    url(r'^query$', views.query, name='query'),


]



from django.conf.urls import url

urlpatterns += [
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^ajax/select_citys/$', views.select_citys, name='select_citys'),
]

sh_p1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from persons.views import showHome
from accounts.views import login_view,logout_view
urlpatterns = [
    url(r'^$', showHome, name='home'),
    url(r'^login$', login_view, name='login_view'),
    url(r'^admin/', admin.site.urls),
    url(r'^persons/', include('persons.urls',namespace='persons')),
    url(r'^likes/', include('likes.urls')),

    url('^', include('django.contrib.auth.urls')),
    url('^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),




]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

persons/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from ckeditor_uploader.fields import RichTextUploadingField
import secretballot
# Create your models here.
class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10,blank=True,null=True)
    national_code = models.CharField(max_length=10,blank=True,null=True)
    num_homes = models.PositiveSmallIntegerField(default=0)
    about = models.TextField(default='asdasd')
    def get_absolute_url(self):
        return "/persons/users/%s/" %self.user.pk
    def __str__(self):
        return str((self.user))
class Home(models.Model):
    name = models.CharField(max_length=30,blank=True,null=True)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    address = models.TextField(default='abc')
    about = models.TextField(default='abc')
    zip_code = models.CharField(max_length=10,default='123')
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    member = models.ForeignKey(User,related_name="homes")


    def __str__(self):
    	return str((self.pk))
    def get_absolute_url(self):
        return "/persons/home/%s/" %self.pk

    def add_a_ana(self):
        return reverse("persons:add_a_ana", kwargs={"id": self.id})
    def remove_a_ana(self):
        return reverse("persons:remove_a_ana", kwargs={"id": self.id})

    def updown(self):
        return reverse("persons:updown", kwargs={"id": self.id})

secretballot.enable_voting_on(Home)


class Picture(models.Model):
    homeid = models.ForeignKey(Home)
    image = models.URLField(blank=True,null=True)
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    def __str__(self):
        return (str(self.pk))
    # def get_absolute_url(self):
    #     return reverse("persons:detail_home", kwargs={"id": self.homeid})
    def get_absolute_url(self):
        return "/persons/home/%s/" %self.homeid

class State(models.Model):
    name = models.CharField(max_length=30,unique=True)
    def __str__(self):
        return (str(self.name))
class City(models.Model):
    ostan = models.ForeignKey(State)
    name = models.CharField(max_length=30,unique=True)
    def __str__(self):
        return (str(self.name))


# comments
class Comment(models.Model):
    home = models.ForeignKey(Home)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    text = RichTextUploadingField()
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    def __str__(self):
        return (str(self.text))


class TrueFalseQuestion(models.Model):
    question = models.CharField(max_length=200,)
    answer = models.BooleanField(default=False)
    home = models.ForeignKey(Home,on_delete=models.CASCADE,default="1")
    def __str__(self):
        return (str(self.question))



    

persons/forms.py
__author__ = 'shahab'
from django import forms
from .models import Home,Picture,Comment,Member,TrueFalseQuestion
from django.contrib.auth import get_user_model

User = get_user_model()

class HomeForm(forms.ModelForm):
    class Meta:
        model = Home
        fields = ['name','address', 'about','zip_code',]
    def save(self,commit=True):
        _home= super(HomeForm,self).save(commit=False)
        if commit:
            _home.save()
        return _home

class ImageForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['image',]
        
class CommentForm(forms.ModelForm):
    # ostan = forms.ChoiceField(choices=ostan,label="witch state",)
    class Meta:
        model = Comment
        fields = ['text']



# class TrueFalseQuestionForm(forms.ModelForm):
#     class Meta:
#         model = TrueFalseQuestion
#         fields = ('question', 'answer', )

# TrueFalseQuestionFormSet = forms.modelformset_factory(
#     TrueFalseQuestion,
#     form=TrueFalseQuestionForm,
#     extra=3
#     )



TFInlineFormSet = forms.inlineformset_factory(
    Home,
    TrueFalseQuestion,
    extra=3,
    fields=('question', 'answer'),


    )



class ArticleForm(forms.Form):
    title = forms.CharField()
    pub_date = forms.DateField()

from django.forms import formset_factory

ArticleFormSet = formset_factory(ArticleForm,extra=2)

persons/views.py
from django.shortcuts import render,redirect,get_object_or_404
from persons.models import Home,Picture,State,City,Comment,Member
from django.template import loader,RequestContext
from django.http import HttpResponse,HttpResponseRedirect
from django.forms import ModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import HomeForm,ImageForm,CommentForm,TFInlineFormSet

from django.http import JsonResponse
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Q
from django.forms import inlineformset_factory

from django.db.models import Count, Min, Sum, Avg
from accounts.models import Like




class SignUpView(CreateView):
    template_name = 'persons/signup.html'
    form_class = UserCreationForm


def add_a_ana(request,id):
    home = Home.objects.get(id=id)
    print("########################################################")
    print(home.name)
    print("########################################################")
    print("home.votes=  "+str(home.votes))
    print("########################################################")
    print("home.total_upvotes=  "+str(home.total_upvotes))
    print("########################################################")
    print("home.total_downvotes=    "+str(home.total_downvotes))
    print("########################################################")
    print("home.vote_total= "+str(home.vote_total))
    print("########################################################")
    home.add_vote("hasan",1)
    print("########################################################")
 
    return HttpResponseRedirect(home.get_absolute_url())


def remove_a_ana(request,id):
    home = Home.objects.get(id=id)
    print("########################################################")
    print(home.name)
    print("########################################################")
    print("home.votes=  "+str(home.votes))
    print("########################################################")
    print("home.total_upvotes=  "+str(home.total_upvotes))
    print("########################################################")
    print("home.total_downvotes=    "+str(home.total_downvotes))
    print("########################################################")
    print("home.vote_total= "+str(home.vote_total))
    print("########################################################")
    home.remove_vote("hasan")
    # ba in dastoor mitavan araye mosbat ya manfi ra remove kard
    print("########################################################")
 
    return HttpResponseRedirect(home.get_absolute_url())

def updown(request,id):
    home = Home.objects.get(id=id)
    print("########################################################")
    print(home.name)
    print("########################################################")
    print("home.votes=  "+str(home.votes))
    print("########################################################")
    print("home.total_upvotes=  "+str(home.total_upvotes))
    print("########################################################")
    print("home.total_downvotes=    "+str(home.total_downvotes))
    print("########################################################")
    print("home.vote_total= "+str(home.vote_total))
    print("########################################################")
    home.add_vote("hasan",-1)
    print("########################################################")
 
    return HttpResponseRedirect(home.get_absolute_url())

def validate_username(request):
    username = request.GET.get('username', None)

    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'این نام کاربری قبلا ثبت نام کرده است.import'
    return JsonResponse(data)



#-------------------------------------------------------------------#
@login_required
def addHome(request):
    current_user = request.user

    template_name='persons/add_home.html'
    state = request.POST.get("state" or None)
    city = request.POST.get("city" or None)
    form1 = HomeForm(request.POST or None, request.FILES or None)
    form2 = ImageForm(request.POST or None, request.FILES or None)
    if form1.is_valid():
        if form2.is_valid():
            _home=form1.save(commit=False)
            _image=form2.save(commit=False)
            _home.member_id= current_user.id
            _home.state= state
            _home.city= city
            _home.save()
            _image.homeid= _home
            _image.save()
            current_user.member.num_homes +=1 
            current_user.member.save()
            return redirect('persons:show_homes')
    states =  State.objects.all()  

    context ={
            "form1":form1,
            "form2":form2,
            "states":states,
                    }

    return render(request,template_name,context)

def select_citys(request):
    ostan_name = request.GET.get('ostan_name'or None)
    ostan_id = State.objects.get(name=ostan_name)
    citys = City.objects.filter(ostan=ostan_id)

    a={}
    for city in citys:
        a[city.name]=city.name

    return JsonResponse(a)


#-------------------------------------------------------------------#
@login_required
def yourHomes(request):
	current_user = request.user
	#f = User.objects.filter(pk=h.member_id)

	_yourHomes= Home.objects.filter(member_id=current_user.id) 
	template_name='persons/yourHomes.html'


	return render(request,template_name,{'yourHomes':_yourHomes,'current_user':current_user})
	


#@login_required
def showHome(request):
    current_user = request.user
    template_name = 'home.html'
    homes = Home.objects.all().order_by("-timestamp")

    query = request.GET.get("q")
    if query:
        homes = homes.filter(
            Q(name__icontains = query)|
            Q(state__icontains = query)|
            Q(member__first_name__icontains = query)|
            Q(member__last_name__icontains = query)|
            Q(member__username__icontains = query)|
            Q(city__icontains = query)
        ).distinct()
	
    return render(request,template_name,{'homes':homes,'user':current_user})

def base(request):
    template_name = 'base.html'
    
    return render(request,template_name,{})

def detail_home(request,home_id):
    h = get_object_or_404(Home,id=home_id)
    f = get_object_or_404(User,pk = h.member_id)
    current_user = request.user

    im_of_this_house = Picture.objects.filter(homeid=home_id).order_by('-timestamp')
    comments = Comment.objects.filter(home=home_id).order_by('-timestamp')
    form = ImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        _image=form.save(commit=False)
        _image.homeid=h
        _image.save()
    form2 = CommentForm(request.POST or None)
    if form2.is_valid():
        _comment=form2.save(commit=False)
        _comment.home=h
        _comment.writer=current_user
        _comment.save()
    liked = Like.has_liked(request.user, h)
    context ={
            "home":h,
            "owner":f,
            "pictures":im_of_this_house,
            "form":form,
            "form2":form2,
            'comments':comments,
            'liked':liked,
                    }
    return render(request,'persons/detail_home.html', context)

def detail_user(request,user_id):
    u = get_object_or_404(User,id=user_id)
    mysite ='google.com'
    context = {'u':u,'mysite':mysite}
    return render(request,'persons/detail_user.html',context)

def home_delete(request,home_id = None):
    instance = get_object_or_404(Home,id=home_id)
    current_user = request.user
    current_user.member.num_homes -=1
    current_user.member.save()
    instance.delete()
    return redirect("persons:show_homes")

def home_update(request,home_id = None):
    instance = get_object_or_404(Home,id=home_id)
    form = HomeForm(request.POST or None,instance = instance)
    # formset = TrueFalseQuestionFormSet(queryset=instance.truefalsequestion_set.all())
    formset = TFInlineFormSet()

    if request.method=="POST":
        formset = TFInlineFormSet(request.POST,queryset=instance.truefalsequestion_set.all())

        if form.is_valid() and formset.is_valid():
            instance = form.save(commit=False)
            instance.save()
            tfqs = formset.save(commit = False)
            for tfq in tfqs:
                tfq.home = instance
                tfq.save()
            return HttpResponseRedirect(instance.get_absolute_url())

    context = {
            "instance": instance,
            "form":form,
            "formset":formset,
         
        }
    template_name = 'persons/home_update.html'
    return render(request, template_name, context)
def delete_image(request,img_id = None):
    img = get_object_or_404(Picture,id=img_id)
    p = img.homeid
    img.delete()
    return HttpResponseRedirect(img.get_absolute_url())
# querys
from django.db import connection
def query(request):
    q1 = User.objects.all()



    q2 = User.objects.filter(username='shab1')

    q3= Home.objects.filter(
                Q(name__icontains = "sh"))
    
    q4 = User.objects.filter(username='shab1').values('username')

    context ={
    'q1':q1.query,
    'q2':q2.query,
    'q3':q3.query,
    'q4':q4.query,
    }

    template_name= 'persons/query.html'
    return render(request,template_name,context)




# formset
# i write this method because i wanted to have a  function for formset
from . import forms
import datetime
def formset_view(request):
    formset = forms.ArticleFormSet(initial=[
     {'title': 'Django is now open source',
      'pub_date': datetime.date.today(),}
            ])
    # formset = forms.ArticleFormSet()

    if request.method == 'POST':
        formset = forms.ArticleFormSet(request.POST)
        if formset.is_valid():

persons/templates/persons/add_home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}home_title{% endblock %}
{% block content %}

<form  method="post"enctype="multipart/form-data" style="text-align: center">
    {% csrf_token %}
    {{ form1.as_p }}
    لینک مربوط به عکس خود را در کادر زیر قرار دهید
    {{ form2.as_p }}


<br/>
استانی که خانه در ان واقع است را انتخاب کنید
فقط میخام تغییری داده باشم.
<br/>
do you here me?
    <select name="state" id="ostan">
      <option ></option>
        {% for state in states %}
          <option value="{{state.name}}">{{ state.name}}</option>
        {% endfor %}
    </select>
      <span class="userror"></span>
    <br/>

شهرستانی که خانه در ان واقع است را انتخاب کنید
<br/>

    <select name="city" id="city">
    <option></option>
    </select>
    <span class="pserror"></span>
                   
<br/>
           <input id="btn" class="btn btn-primary" type="submit" value="send" />

</form>

{{user.username}}


{% endblock %}
    

    {% block jquery %}
  
$("#sh").css( { marginLeft : "550px", marginRight : "200px" ,color:"blue"} );
$("#id_image").css( { marginLeft : "550px", marginRight : "200px" } );
  
    $("#ostan").change(function () {
      var ostan_name = $(this).val();
      <!-- alert(ostan_name); -->
      console.log(typeof ostan_name)


      $.ajax({
        url: "{% url 'persons:select_citys' %}",
        data: {
          'ostan_name': ostan_name,
        },
      success: function(data){
  console.log(data);
$("#city").empty(); 
   var op = $('<option></option>').attr("value", "").text("");
 var i;
  for(i in data){
  <!-- alert(i); -->
  <!-- alert(data[i]); -->
   var option = $('<option></option>').attr("value", i).text(data[i]);
$("#city").append(option);
 
 } }
  });
      });
  
$('#btn').click(function(){

  var username=$("#state").val();
  var password=$("#city").val();
  var error = false;
  if (username =='') {
    error = true;
    $('.userror').html("<font color='red'>*</font>");
  }
  
  if (password =='') {
    error = true;
    $('.pserror').html("<font color='red'>*</font>");
  }
  if (error) {return false;}

  });
    
{% endblock %}

persons/templates/persons/detail_home.html
{% extends "base.html" %}
{% load staticfiles %}
{% load likes_inclusion_tags %}
{% block head_title %}home_title{% endblock %}
{% block content %}







{% likes home %}

<a href="{{home.add_a_ana}}">add_a_ana</a>
<br>
<a href="{{home.remove_a_ana}}">remove_a_ana</a>
<br>
<a href="{{home.updown}}">updown</a>


<div id="po" class="thumbnail">
    <div style="text-align:center">
<h3>تاریخ معرفی</h3>
 {{ home.timestamp }}
        <hr>

<h3>نام</h3>
{{home.name}}
<hr>
<hr>
<hr/>
<h3>استان</h3>
{{home.state}}
<hr/>
<h3>شهر</h3>
{{home.city}}
<hr/>
<h3>آدرس</h3>
{{home.address|linebreaks}}
<hr/>

{{home.about}}
<hr/>


<br/>
<a href="{% url 'persons:users' user_id=owner.pk %}">{{owner.username}}</a>
<br/>شماره تلفن:{{owner.member.phone_number}}


<!-- this is comment -->
<!-- <img src="{{home.image.url}}" />
 -->

<hr>
</div>
{% for p in pictures %}
    <img id="img" src="{{p.image}}" />
    {% if user.username ==  owner.username %}

    <a href="/persons/image/{{p.id}}/delete/">delete this picture</a>
    {% endif %}

    <hr>

{% endfor%}
    <div style="text-align:center">
{% if user.is_authenticated %}
    {% if liked %}
        you like this home
    {% else %}
            <button id="btnLike" class="btn btn-info btn-lg">
            <i class="fa fa-thumbs-up" aria-hidden="true"></i>like     
            </button>
            <div id="message"></div>
    
    {% endif %}        

{% endif %}
    </div>
</div>        

    {% if user.username ==  owner.username %}
<form  method="post"enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input  type="submit" value="Submit" />
</form>
		<a href="/persons/{{home.id}}/delete/">delete this home</a>
        <br/>
		<a href="/persons/{{home.id}}/edit/">edit this home</a>
{% endif %}

</div>

<!-- Comments -->
<div id="po" class="thumbnail">
<div style="text-align:center">
{% for com in comments %}
   <h4><a href="/persons/users/{{com.writer.id}}/">{{com.writer}}</a></h4> 


{% autoescape off %}
{{com.text}}
{% endautoescape %}
    <hr>

{% endfor%}

    {% if user.is_authenticated %}

<form  method="post">
    {% csrf_token %}
    {{ form2.media }}
    {{ form2.as_p }}
    <input  type="submit" value="ارسال نظر" />
</form>

    {% endif %}

</div>
</div>

{% endblock %}



{% block jquery %}
var a = "{{home.id}}";

       $("#btnLike").click(function () {
            $.ajax({
                    url: "{% url 'accounts:like' %}",
                    data: {
                        'home_id': a,
                    },
                    success: function(data){
                    {# alert(data["message"]) #}
                   var message = data["message"];
                   message =
                $("#message").html(message)
         
                 
                 } }     )


            });
   
{% endblock jquery %}

persons/templates/persons/detail_user.html
{% extends "base.html" %}
{% load staticfiles %}

{% load humanize %}

{% block head_title %}home_title{% endblock %}
{% block content %}
this is from detail user
    <div id="po" class="thumbnail">
<div style="text-align:center">
{{u.username}}
<hr/>
<h3>نام</h3>
{{u.first_name}}
<hr/>

<img src="{{home.image_url}}">
<h3>نام خانوادگی</h3>
{{u.last_name}}
<hr/>


<h3>کد ملی</h3>
{{u.member.national_code}}
<hr/>


<h3>شماره تلفن</h3>
{{u.member.phone_number}}
<hr/>
</div>
</div>

    <hr/>
    <hr/>
{{ u.home_set.all }}
    <br>
{{ u.home_set.count }}

    <br>
{{ u.home_set.count|apnumber }}

<hr>
 {% with member=u.member  %}
 {{ name }}
    {{ member.about|linebreaks }}
    content:{{ member.about|wordcount }}words

    {% if member.about|wordcount <= 10 %}
        {{ member.about }}
    {% else %}
        {{ member.about|truncatewords:5 }}
     {% endif %}

     <div>
     you can contact with me in:{{ u.email|urlize }}
     my site is:{{ mysite|urlize }}
     </div>
 {% endwith %}
{% endblock %}

persons/templates/persons/formset.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}formset{% endblock %}
{% block content %}

<form  method="post">
    {% csrf_token %}
    {{ formset.as_p }}

        <input type="submit" value="Submit" />

 </form>


 {% endblock %}

persons/templates/persons/home_update.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}home_title{% endblock %}
{% block content %}
<h1>home_update.html</h1>
<h1 id="sh">shahb</h1>
<form  id="myForm" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{formset.management_form}}
    <table role="grid"class="stack kover" >
    	<thead>
    		<th scope="col" class="text-center">question</th>
    		<th scope="col" class="text-center">it has</th>
    	
    	</thead>
    	<tbody>
    		{% for form in formset %}
    		<tr>
    			<td>{{form.question}}</td>
    			<td>{{form.answer}}</td>
    	
    		</tr>
    			
    		{% endfor %}
    	</tbody>
    	
    </table>

        <input type="submit" value="Submit" />
 </form>
<h1 id="sh">shahb</h1>
 {% endblock %}


 {% block jquery %}

$("#sh").css( { marginLeft : "550px", marginRight : "200px" ,color:"blue"} );
   
                   $('#myForm tbody tr').formset({
                   prefix: '{{ formset.prefix }}'
               });
   
     {% endblock %}

persons/templates/persons/query.html
{% load staticfiles %}

{{q1}}
<hr>
{{q2}}

<hr>
{{q3}}


<hr>
{{q4}}

persons/templates/persons/signup.html
{% extends 'base.html' %}

{% block jquery %}
 
    $("#id_username").change(function () {
      var username = $(this).val();


      $.ajax({
        url: "{% url 'persons:validate_username' %}",
        data: {
          'username': username
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
          }
        }
      });

    });
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

persons/templates/persons/yourHomes.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}home_title{% endblock %}
{% block content %}




yourHomes:
<br/>
{%if yourHomes%}
{% for home in yourHomes%}
		<a href="/persons/home/{{home.id}}/">{{home.name}}</a>
		<br/>
	{% endfor%}
{% else %}
<p>شما هنوز خانه ای برای فروش به ما معرفی نکرده اید</p>
{% endif %}
if you have a house and you would like to soil it you can do it
		<a href="{% url 'persons:add_home' %}">here</a>
<hr/>

{% endblock %}