accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^register$', views.register, name='register'),
    url(r'^information$', views.information, name='information'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^like$', views.like, name='like'),

]

persons/urls.py
from django.conf.urls import url

from . import views

app_name = 'persons'
urlpatterns = [
    url(r'^add_home$', views.addHome, name='add_home'),
    url(r'^base$', views.base, name='base'),
    url(r'^$', views.showHome, name='show_homes'),
    url(r'^yourHomes/$', views.yourHomes, name='yourHomes'),


    url(r'^(?P<id>[0-9]+)/$', views.remove_a_ana, name='remove_a_ana'),
    url(r'^(?P<id>[0-9]+)/$', views.updown, name='updown'),
    url(r'^(?P<id>[0-9]+)/$', views.add_a_ana, name='add_a_ana'),

    
    url(r'^home/(?P<home_id>[0-9]+)/$', views.detail_home, name='detail_home'),
    url(r'^image/(?P<img_id>[0-9]+)/delete/$', views.delete_image, name='delete_image'),
    url(r'^(?P<home_id>[0-9]+)/delete/$', views.home_delete, name='delete'),
    url(r'^(?P<home_id>[0-9]+)/edit/$', views.home_update, name='update'),
    url(r'^users/(?P<user_id>[0-9]+)/$', views.detail_user, name='users'),
    url(r'^formset$', views.formset_view, name='formset'),
    url(r'^query$', views.query, name='query'),


]



from django.conf.urls import url

urlpatterns += [
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^ajax/select_citys/$', views.select_citys, name='select_citys'),
]

sh_p1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from persons.views import showHome
from accounts.views import login_view,logout_view
urlpatterns = [
    url(r'^$', showHome, name='home'),
    url(r'^login$', login_view, name='login_view'),
    url(r'^admin/', admin.site.urls),
    url(r'^persons/', include('persons.urls',namespace='persons')),
    url(r'^likes/', include('likes.urls')),

    url('^', include('django.contrib.auth.urls')),
    url('^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),




]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

persons/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from ckeditor_uploader.fields import RichTextUploadingField
import secretballot
# Create your models here.
class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10,blank=True,null=True)
    national_code = models.CharField(max_length=10,blank=True,null=True)
    num_homes = models.PositiveSmallIntegerField(default=0)
    about = models.TextField(default='asdasd')
    def get_absolute_url(self):
        return "/persons/users/%s/" %self.user.pk
    def __str__(self):
        return str((self.user))
class Home(models.Model):
    name = models.CharField(max_length=30,blank=True,null=True)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    address = models.TextField(default='abc')
    about = models.TextField(default='abc')
    zip_code = models.CharField(max_length=10,default='123')
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    member = models.ForeignKey(User,related_name="homes")


    def __str__(self):
    	return str((self.pk))
    def get_absolute_url(self):
        return "/persons/home/%s/" %self.pk

    def add_a_ana(self):
        return reverse("persons:add_a_ana", kwargs={"id": self.id})
    def remove_a_ana(self):
        return reverse("persons:remove_a_ana", kwargs={"id": self.id})

    def updown(self):
        return reverse("persons:updown", kwargs={"id": self.id})

secretballot.enable_voting_on(Home)


class Picture(models.Model):
    homeid = models.ForeignKey(Home)
    image = models.URLField(blank=True,null=True)
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    def __str__(self):
        return (str(self.pk))
    # def get_absolute_url(self):
    #     return reverse("persons:detail_home", kwargs={"id": self.homeid})
    def get_absolute_url(self):
        return "/persons/home/%s/" %self.homeid

class State(models.Model):
    name = models.CharField(max_length=30,unique=True)
    def __str__(self):
        return (str(self.name))
class City(models.Model):
    ostan = models.ForeignKey(State)
    name = models.CharField(max_length=30,unique=True)
    def __str__(self):
        return (str(self.name))


# comments
class Comment(models.Model):
    home = models.ForeignKey(Home)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    text = RichTextUploadingField()
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    def __str__(self):
        return (str(self.text))


class TrueFalseQuestion(models.Model):
    question = models.CharField(max_length=200,)
    answer = models.BooleanField(default=False)
    home = models.ForeignKey(Home,on_delete=models.CASCADE,default="1")
    def __str__(self):
        return (str(self.question))



    

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}{% endblock %} cfe</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>





<!-- Latest compiled and minified CSS -->
<!-- jQuery library -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<link href="{% static 'css/my.css' %}" rel="stylesheet">
<style>
    {% block styles %}
    {% endblock %}
.background_img_thumb{
    width:100%;
            height:100%;
            background-size:cover;
            background-repeat:no-repeat;
            background-position:center;
}
</style>
   
  </head>

  <body>


{% include "navebar.html" %}

    {% block jombotron %}
    {% endblock %}
    <div class="container">

{% block content %}
{% endblock %}
     
    </div> <!-- /container -->
<script type="text/javascript">
    {% block javascript %}
    {% endblock %}
</script>

    <!-- Bootstrap core JavaScript
    ================================================== -->
<script>
$(document).ready(function(){
    {% block jquery %}
    {% endblock %}
});
</script>

   <footer style="color: blue">created by shahb emami</footer>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}home_title{% endblock %}
{% block content %}

{% if homes %}
{% for home in homes %}
{% for image_of_home in home.picture_set.all %}

    <div id="po" class="thumbnail">

    <a href="{% url 'persons:detail_home' home_id=image_of_home.homeid %}"><img class="img-rounded" alt="Cinque Terre" id="img"src="{{image_of_home.image}}" /></a>
      
</div>
	{% endfor%}
{% endfor %}



 


{% else %}
	they are not any home for this search


{% endif %}


{% endblock %}


   {% block jquery %}

       $.ajax({
    url: '',
    type: 'get', // This is the default though, you don't actually need to always mention it
    success: function(data) {
        <!-- alert(data); -->
        <!-- alert("shahab"); -->
    },
    failure: function(data) { 
        alert('Got an error dude');
    }
}); 
    {% endblock %}

templates/nav_best_user.html
<a href="{% url 'persons:users' user_id=best.user_id %}">{{best.user}}</a>

templates/navebar.html
{% load staticfiles %}


<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">KhaneYabi</a>
        </div>
   
          <form class="navbar-form navbar-right" role="search" action="{% url 'home' %}">
          <div class="form-group">
            <input type="text" class="form-control" name="q" placeholder="Search">
                </div>
               <button type="submit"  class="btn btn-default">Submit</button> 
               </form>
          <ul class="nav navbar-nav navbar-right">
           
            <li><a href="/admin">login as admin</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            <li><a href="{% url 'accounts:information' %}">information</a></li>
            <li><a href="{% url 'persons:yourHomes' %}">{{user.username}}</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'accounts:register' %}">Register</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/test.html
{{home.name}}